# Generated by Django 5.0.1 on 2024-03-03 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherdata',
            name='icon_url',
            field=models.URLField(null=True),
        ),
    ]
